import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import './globals.css';
import { Toaster } from 'sonner';
import { AppProvider } from './context/provider';
import type { ReactNode } from 'react';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: {
  children: ReactNode;
  modal: ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} bg-theme-blue antialiased`}
      >
        <AppProvider>
          <>
            {children}
            {modal}
            <Toaster
              toastOptions={{
                classNames: { error: 'border-red-500' },
                duration: 3000,
              }}
            />
          </>
        </AppProvider>
      </body>
    </html>
  );
}
