export const participants = [
  {
    id: 1,
    firstName: "John",
    lastName: "Doe",
    parish: "St. Peter's",
    score: 85,
  },
  {
    id: 2,
    firstName: "Grace",
    lastName: "Adams",
    parish: "Holy Trinity",
    score: 90,
  },
  {
    id: 3,
    firstName: "Michael",
    lastName: "Okafor",
    parish: "St. Joseph's",
    score: 78,
  },
  {
    id: 4,
    firstName: "Chinwe",
    lastName: "Obi",
    parish: "Our Lady of Lourdes",
    score: 88,
  },
  {
    id: 5,
    firstName: "Samuel",
    lastName: "Ibrahim",
    parish: "Sacred Heart",
    score: 92,
  },
  {
    id: 6,
    firstName: "Esther",
    lastName: "Bello",
    parish: "Christ the King",
    score: 85,
  },
  {
    id: 7,
    firstName: "Emeka",
    lastName: "Eze",
    parish: "St. Michael's",
    score: 80,
  },
  {
    id: 8,
    firstName: "Ngozi",
    lastName: "Nwankwo",
    parish: "St. Patrick's",
    score: 75,
  },
];
